<<<<<<< HEAD:matches/migrations/0001_initial.py
# Generated by Django 2.2.7 on 2019-11-10 08:03
=======
# Generated by Django 2.2.5 on 2019-11-10 08:06
>>>>>>> 9b6aea0177d7b90621a9097e7cdb0498d53e7131:users/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matches_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id_1', models.IntegerField()),
                ('item_id_2', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
