# Generated by Django 2.2.5 on 2019-11-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matches_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id_1', models.IntegerField()),
                ('item_id_2', models.IntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
