# Generated by Django 2.2.7 on 2019-11-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='email',
        ),
    ]
