# Generated by Django 2.2.5 on 2019-11-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
