# Generated by Django 2.2.5 on 2019-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
                ('traded', models.BooleanField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
