# Generated by Django 2.2.5 on 2019-11-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
                ('value_low', models.IntegerField()),
                ('value_high', models.IntegerField()),
                ('description', models.TextField()),
                ('traded', models.BooleanField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
