# Generated by Django 2.2.5 on 2019-11-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='value_high',
        ),
        migrations.AddField(
            model_name='item',
            name='value_low',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
